# Generated by Django 4.2.10 on 2024-03-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.IntegerField(choices=[(0, 'available'), (1, 'reserved'), (2, 'sold')], default=0),
        ),
    ]
